### ISSUE TITLE
Further functionality suggestion

### ISSUE THREAD

**Issue by Nusob888** [jackbibby1/SCPA#11]
Dear Jack, 

I have got SCPA up and running and it is proving to be really useful. 
I was wondering if there are any plans to include bidirectional analysis of comparator groups? e.g. negative fold enrichment/qvalues. 

Currently, to do this I am generating loops of bidirectional comparisons, but it would be great to have this option built in.

**Comment by jackbibby1** [comment]
Hi,

Ah, good to hear. 

Because of the multivariate assessment in SCPA, it's detecting more than just enrichment of gene expression, so it's not really possible to reduce this down/assign a directional signal to the Qval. For example, there are plenty of pathways that show large changes in multivariate distribution (large Qval), but zero directional change when you look at fold changes. If you want an example, see Figure 4D-J in our paper [here](https://www.biorxiv.org/content/10.1101/2022.02.07.478807v1.full.pdf+html) where we show that these pathways are important.

I'm not completely sure what you're doing with the loops (happy to look at some specific code of yours), but In the SCPA output, there is a fold change value (FC), which is a running sum of mean changes in gene expression for that pathway... so this will have a positive/negative directional value. If you wanted to assign some directionality as a secondary informative value, you can use this and plot something like Figure 4D in the above link. I would generally advise against using the fold changes/directionality as a primary measure of pathway activity though, and just use the Qvals.

**Comment by Nusob888** [comment]
Hi, 
Many thanks for the explanation, I think I am a little more oriented to the output now. I think the tutorials filtered a few columns I had not been aware of and my data did not have negative fold change pathways, hence the confusion. 

On a side note, it would be really useful if the tutorials can expand on how to pull out genes contributing most to the highest ranked pathways e.g. the code used to identify the defensin genes in the cross tissue analysis. Or, whether that could be incorporated as a function?
