### ISSUE TITLE
parallel implementation 

### ISSUE THREAD

**Issue by ruiye88** [jackbibby1/SCPA#17]
Hi,

I really like the concept proposed by SCPA and would like to try it out. I noticed that the current method has a downsample option and it becomes pretty computationally intensive with a large number of cells. Just wondering that are you planning to add parallelization or any other optimization steps in the future so that it can work faster for larger datasets? Thanks.

**Comment by jackbibby1** [comment]
Hi,

Thanks. Unfortunately there isn't a way to further optimize the distribution testing itself, which is the most time-intensive step. Generating all the pathway specific expression matrices for the comparison (performed within the `compare_pathways()` function) is the most memory-intensive step, which I assume is the issue you're running into. I'll see if I can optimize this so the memory burden is distributed more across the function, and I can let you know if I come up with something. 

This being said, unless you have a good reason to increase the downsampling value, I would generally leave it at 500 cells. In addition to the time and memory advantages, the reason we recommend downsampling to 500 cells per comparative group is that we've seen this is more than enough cells for SCPA to still be really sensitive -- even fewer than 500 cells is fine. We've also seen that 500 cells is typically a good sampling representation of most population sizes, assuming the upstream clustering is accurate. I.e. if we run repeated comparisons of two reasonably large clusters (~2-3k cells) that have been downsampled to 500 cells each, we get very high concordance of qvals. Going above 500 cells generally means limited output benefit at a large computational cost.

If you're wanting to do a systems level analysis e.g. like [this](https://jackbibby1.github.io/SCPA/articles/systematic_tissue_comparison.html) where you have 1000s+ of pathways and many cell types, I would typically recommend running this on a cluster because of the memory requirements. As some sort of reference, I recently ran a pathway comparison (~5000 gene sets) across T cells from 24 tissues in the human atlas (~80k cells total), and this took ~4 hours using ~40gb RAM and a single core.

Just let me know if there's anything else

Jack

**Comment by ruiye88** [comment]
> Hi,
> 
> Thanks. Unfortunately there isn't a way to further optimize the distribution testing itself, which is the most time-intensive step. Generating all the pathway specific expression matrices for the comparison (performed within the `compare_pathways()` function) is the most memory-intensive step, which I assume is the issue you're running into. I'll see if I can optimize this so the memory burden is distributed more across the function, and I can let you know if I come up with something.
> 
> This being said, unless you have a good reason to increase the downsampling value, I would generally leave it at 500 cells. In addition to the time and memory advantages, the reason we recommend downsampling to 500 cells per comparative group is that we've seen this is more than enough cells for SCPA to still be really sensitive -- even fewer than 500 cells is fine. We've also seen that 500 cells is typically a good sampling representation of most population sizes, assuming the upstream clustering is accurate. I.e. if we run repeated comparisons of two reasonably large clusters (~2-3k cells) that have been downsampled to 500 cells each, we get very high concordance of qvals. Going above 500 cells generally means limited output benefit at a large computational cost.
> 
> If you're wanting to do a systems level analysis e.g. like [this](https://jackbibby1.github.io/SCPA/articles/systematic_tissue_comparison.html) where you have 1000s+ of pathways and many cell types, I would typically recommend running this on a cluster because of the memory requirements. As some sort of reference, I recently ran a pathway comparison (~5000 gene sets) across T cells from 24 tissues in the human atlas (~80k cells total), and this took ~4 hours using ~40gb RAM and a single core.
> 
> Just let me know if there's anything else
> 
> Jack

Hi Jack,

Thank you for the quick response. I have a dataset with ~60K cells with two groups (control and disease) that I want to compare. For each group, I have like around 20 samples. So if downsampled to 500 cells per group it seems that there will be a pretty high chance that I may lose a lot of information. 

For your recent run of 5000 gene sets on 80k cells, did you use all the cells or you also downsampled your data? I tried to downsample my data to about 100 cells per sample which means  I have ~4000 cells in total. Then I tried to run the downsampled cells with ~2000 gene sets but seems that it's taking much longer than 4 hours. 

Best,
Rui

**Comment by jackbibby1** [comment]
Hi Rui,

Ah, I think I see what you mean. You won't supply each of your samples here separately (I assume each sample is a different donor?)... you'll need to supply samples that have been combined by some sort of grouping -- likely cell type/cluster. Have you done some sort of upstream clustering, or are you just treating the groups as if it was bulk RNA sequencing?

If you've done some clustering to identify cell types etc., I would compare pathways in specific cell types/clusters between healthy and disease. Something like [this tutorial](https://jackbibby1.github.io/SCPA/articles/disease_comparison.html), where you just need to loop over all your cell types, and split the comparison by disease state. In this comparison, each cluster contains cells from multiple donors. So you will just supply two samples per comparison e.g. `t_cell_healthy` and `t_cell_disease`, where your t_cell populations will be a combination of all donors you have per disease state.

If you want to treat your data as bulk RNA-sequencing and compare all cells in healthy versus all cells in disease, you can just extract x number of cells from each and supply two populations. e.g.

```
scpa_out <- compare_pathways(samples = list(healthy, disease),
                             pathways = pathways,
                             downsample = some_number)
```

I would generally advise against this second approach though, unless you just want a really general idea of what's going on, because you'll lose lots of information by merging all the cell types. Here bulk RNA-seq would be much more appropriate.

Hope I'm understanding properly. It'll be easier if you can send over the code that you're using so I can get a handle on what you're trying to do.

Jack

**Comment by jackbibby1** [comment]
RE efficiency in the `compare_pathways/seurat/sce()` functions, memory usage in SCPA v1.3.0 is now significantly improved, so users will not be limited by RAM availability. See https://jackbibby1.github.io/SCPA/news/index.html
