### ISSUE TITLE
speed up computation with parallel and multi-cores

### ISSUE THREAD

**Issue by quyaingo** [jackbibby1/SCPA#36]
Hello,

Even with multiple cores used for paralleling, the computation still takes a very long time and enormous computing memory for large data set (with cell number > 8000). I wouldn't want to sample down in order to avoid information loss. Is there any bench-marking done to show the minimum down-sample size that minimizes information loss?

Also, is there future development to improve the computation speed and memory usage for large data sets?

Thank you!

**Comment by jackbibby1** [comment]
Hi,

Are you using 8000 cells per population for the comparison? If so, this will likely be quite excessive (both from the SCPA side and computationally). Assuming that the upstream clustering is looking good, I think that sampling somewhere in the region of 500 cells from the cluster is generally a fair representation, and adding more cells won't really improve your output. As a quick example using the KEGG database and looping SCPA through the same two T cell clusters (3000+ cells per population), you can see that there's a very high correlation in qval when randomly downsampling to 500 cells. e.g. 

```
df <- readRDS("memory_t_cell.rds")
pathways <- msigdbr("Homo sapiens") %>%
  filter(grepl("kegg", gs_name, ignore.case = T)) %>%
  format_pathways()

scpa_out <- list()
for (i in 1:2) {
  scpa_out[[i]] <- compare_seurat(df, 
                                  group1 = "Cell_Type",
                                  group1_population = c("Tcm", "Th1"), #~3000 cells per population here
                                  pathways = pathways, 
                                  parallel = T,
                                  cores = 2)
}

plot(scpa_out[[1]]$qval, scpa_out[[2]]$qval,
     xlab = "Comparison 1",
     ylab = "Comparison 2")

```

<img width="297" alt="Screenshot 2023-02-08 at 09 54 26" src="https://user-images.githubusercontent.com/59352321/217565240-f36958e5-d9f5-4048-b95a-3361f31811c1.png">

Also, RE your point in sensitivity, we did some brief benchmarking on simulated datasets (see broad overview on our simulation [here](https://github.com/jackbibby1/scpa_paper/blob/main/figure_1.R#L48)) and we see that SCPA is very sensitive even down to 100-200 cells, so 500 cells is plenty to detect a difference if there is one. Here's a summary of the downsampling sensitivity using different cell numbers (deFacLoc and deProb = 0.5 in splatter).

<img width="300" alt="Screenshot 2023-02-08 at 10 06 14" src="https://user-images.githubusercontent.com/59352321/217568216-27b3b37e-ab21-410f-a03e-f9ed9ee1fe7e.png">

RE memory usage -- I think it's pretty efficient at the minute and there's not much we can do to improve this further. As an example, using 2 cores and 500 cells per population, I can easily run comparisons of 5000+ pathways locally on pretty simple machine (8GB RAM). You're likely running into computational issues because you're using so many cells on multiple cores, meaning that there are lots of pathway matrices and comparisons being generated by SCPA in parallel. If you really want to run SCPA using 8000 cells, the other option is to run it on a cluster, where you'll have access to much more computing power

Jack

**Comment by quyaingo** [comment]
Thank you very much for the explanation.

However, I'm not comparing 2 clusters. I'm comparing 2 conditions where cells in each condition come from different cluster combinations; hence the large number of cells per condition in the comparison.

I think down-sampling in my case would be risky. The example you gave compares 2 conditions within each cluster, so I guess it's fine with down-sampling.

I would appreciate having more feedback on this.

**Comment by jackbibby1** [comment]
Hmm, OK. I don't know what data you're dealing with, but I would generally avoid combining clusters for the comparison because even if you use all 8000 cells, you'll lose information with all the noise that's introduced by different cell types. I would be tempted to do a comparison of individual clusters across conditions, and then compare the shared and unique pathway signatures to get an overview of generally or specifically perturbed pathways i.e. like Fig5 of [our paper](https://www.cell.com/cell-reports/pdf/S2211-1247(22)01571-6.pdf) or [this tutorial](https://jackbibby1.github.io/SCPA/articles/systematic_tissue_comparison.html). This will be a cleaner output and will preserve the most information.

If you're going to combine clusters in a bulk-like comparison between conditions, then I don't imagine downsampling will have a huge impact on your output, as long as you choose something reasonable (maybe 1-2k in your situation). I think that in this scenario, any broad signatures will still be identified

**Comment by quyaingo** [comment]
Ok, I'll try max 2000 cells.

Many thanks!
